/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import com.mysql.jdbc.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;


public class Escuela extends javax.swing.JFrame {
    public static String url = "jdbc:mysql://localhost:3306/escuela?autoReconnet=true&useSSL=false";
    public static String usuario = "root";
    public static String contraseña = "1234";
    PreparedStatement ps;
    ResultSet rs;
     public Connection geConnection(){
      Connection conexion=null;
      try{
        Class.forName("com.mysql.jdbc.Driver");
        conexion = (Connection)DriverManager.getConnection(url,usuario,contraseña);
    
      }catch(Exception ex){
          System.err.println("Error, "+ex);
      }
  
   return conexion;
  }
   
    public Escuela() {
        
        initComponents();
        idPersonatxt.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscuela = new javax.swing.JPanel();
        txtPass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNOMBRE = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNacimiento = new javax.swing.JTextField();
        jcboGenero = new javax.swing.JComboBox<>();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        idPersonatxt = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("nacimiento:");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("genero:");

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        txtNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacimientoActionPerformed(evt);
            }
        });

        jcboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masculido", "femenino" }));
        jcboGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboGeneroActionPerformed(evt);
            }
        });

        btnInsertar.setText("insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Clave");

        javax.swing.GroupLayout panelEscuelaLayout = new javax.swing.GroupLayout(panelEscuela);
        panelEscuela.setLayout(panelEscuelaLayout);
        panelEscuelaLayout.setHorizontalGroup(
            panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscuelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEscuelaLayout.createSequentialGroup()
                        .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelEscuelaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(43, 43, 43)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEscuelaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(49, 49, 49)
                                .addComponent(txtNOMBRE))
                            .addGroup(panelEscuelaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)
                                .addComponent(txtNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEscuelaLayout.createSequentialGroup()
                                .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelEscuelaLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jcboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEscuelaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                        .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelEscuelaLayout.createSequentialGroup()
                                                .addComponent(btnModificar)
                                                .addGap(52, 52, 52)
                                                .addComponent(btnEliminar))
                                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEscuelaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelEscuelaLayout.createSequentialGroup()
                                .addComponent(idPersonatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(panelEscuelaLayout.createSequentialGroup()
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(25, 25, 25))))
                    .addGroup(panelEscuelaLayout.createSequentialGroup()
                        .addComponent(btnInsertar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelEscuelaLayout.setVerticalGroup(
            panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscuelaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idPersonatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEscuela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void jcboGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboGeneroActionPerformed
       
    }//GEN-LAST:event_jcboGeneroActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     Connection conexion;
     try{
         conexion = geConnection();
         ps = conexion.prepareStatement("select * from persona where clave = ?");
         ps.setInt(1,Integer.parseInt(txtPass.getText()));
         rs=ps.executeQuery();
         if(rs.next()){
            idPersonatxt.setText(String.valueOf(rs.getInt("idpersona")));
             //(nombre,clave,apelliw7do,naciemiento,genero)
            txtApellido.setText(rs.getString("apellido"));
            txtNOMBRE.setText(rs.getString("nombre"));
            txtNacimiento.setText(""+rs.getDate("naciemiento"));
            jcboGenero.setSelectedItem(rs.getString("genero"));
            txtClave.setText(rs.getString("clave"));
            JOptionPane.showMessageDialog(null,"Registro encontrado");
         }else{
             JOptionPane.showMessageDialog(null,"Registro no encontrado");
         }
         conexion.close();
     }catch(Exception ex){
         System.err.println("Error, "+ex);  
     }
     
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacimientoActionPerformed
     Connection conexion;
     try{
       conexion = geConnection();
       ps = conexion.prepareStatement("insert into persona(nombre,clave,apellido,naciemiento,genero) values (?,?,?,?,?)");
       ps.setString(1, txtNOMBRE.getText());
       ps.setInt(2,Integer.parseInt(txtClave.getText()));
       ps.setString(3, txtApellido.getText());
       ps.setDate(4, Date.valueOf(txtNacimiento.getText()));
       ps.setString(5, jcboGenero.getSelectedItem().toString());
       //actualizar la tabla de base de datos
       int resultado = ps.executeUpdate();
       if(resultado>0){
           JOptionPane.showMessageDialog(null,"registro guardado");
       }else{
           JOptionPane.showMessageDialog(null,"ha ocurrido un error");
       }
       conexion.close();
  
     }catch(Exception ex){
         System.err.println("Error, "+ex);
     }
        
        
    }//GEN-LAST:event_txtNacimientoActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
    
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
      Connection conexion;
     try{
       conexion = geConnection();
       //persona(nombre,clave,apellido,naciemiento,genero)
       ps = conexion.prepareStatement("update persona set nombre =?,clave=?,apellido=?,naciemiento=?,genero=? where idpersona=?");
       ps.setString(1, txtNOMBRE.getText());
       ps.setInt(2,Integer.parseInt(txtClave.getText()));
       ps.setString(3, txtApellido.getText());
       ps.setDate(4, Date.valueOf(txtNacimiento.getText()));
       ps.setString(5, jcboGenero.getSelectedItem().toString());
       ps.setInt(6,Integer.parseInt(idPersonatxt.getText()));
       int resultado = ps.executeUpdate();
       if(resultado>0){
           JOptionPane.showMessageDialog(null,"se modifico correctamente el registro");
           LimpiarFrame(panelEscuela);
       }else{
          JOptionPane.showMessageDialog(null,"no modifico correctamente el registro");  
       }
       conexion.close();
       
     }catch(Exception ex){
         
     }
     
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      if(idPersonatxt.getText().equals("")){
        JOptionPane.showMessageDialog(null,"debe buscar una persona"
                                           + "\npara poder ELIMINAR");
      }else{
        Connection conexion;
     try{
       conexion = geConnection();
       //persona(nombre,clave,apellido,naciemiento,genero)
       ps = conexion.prepareStatement("delete from persona where idpersona=?");
       ps.setInt(1,Integer.parseInt(idPersonatxt.getText()));
       int resultado = ps.executeUpdate();
       if(resultado>0){
           JOptionPane.showMessageDialog(null,"se elimino correctamente el registro");
           LimpiarFrame(panelEscuela);
       }else{
          JOptionPane.showMessageDialog(null,"no se elimino correctamente el registro");  
       }
      conexion.close();
       
     }catch(Exception ex){
         System.err.println("Error, "+ex);  
     }
      }
     
    }//GEN-LAST:event_btnEliminarActionPerformed
  private void LimpiarFrame(JPanel panel){
   for(int i=0; i<panel.getComponents().length;i++){
      if(panel.getComponents()[i] instanceof JTextField){
          JTextField  obj = (JTextField)panel.getComponents()[i] ;
          obj.setText("");    
      } 
   }   
      
  }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escuela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JTextField idPersonatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jcboGenero;
    private javax.swing.JPanel panelEscuela;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNOMBRE;
    private javax.swing.JTextField txtNacimiento;
    private javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables
}
