/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author JOSE
 */
public class vistaPersona extends javax.swing.JFrame {

    /**
     * Creates new form vistaPersona
     */
    public vistaPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jSplitPane1 = new javax.swing.JSplitPane();
        panel = new javax.swing.JPanel();
        btnElimiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cboAño = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        cboMes = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        cboDia = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        txtNOMBRE = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jcboGenero = new javax.swing.JComboBox<String>();
        botonBuscar = new javax.swing.JButton();
        idPersonatxt = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        txtClave = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        txtPass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        Men0 = new javax.swing.JMenuBar();
        MEN1 = new javax.swing.JMenu();
        btnMostrarTabla = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setPreferredSize(new java.awt.Dimension(418, 395));
        panel.setLayout(null);

        btnElimiar.setText("Eliminar");
        panel.add(btnElimiar);
        btnElimiar.setBounds(10, 470, 100, 32);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        panel.add(jLabel2);
        jLabel2.setBounds(20, 160, 54, 17);

        cboAño.setBackground(new java.awt.Color(204, 255, 255));
        cboAño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        panel.add(cboAño);
        cboAño.setBounds(100, 270, 80, 26);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Apellido:");
        panel.add(jLabel3);
        jLabel3.setBounds(20, 220, 60, 17);

        cboMes.setBackground(new java.awt.Color(204, 255, 255));
        cboMes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cboMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto ", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        panel.add(cboMes);
        cboMes.setBounds(190, 270, 120, 25);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("nacimiento:");
        panel.add(jLabel4);
        jLabel4.setBounds(10, 270, 77, 17);

        cboDia.setBackground(new java.awt.Color(204, 255, 255));
        cboDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cboDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDiaActionPerformed(evt);
            }
        });
        panel.add(cboDia);
        cboDia.setBounds(330, 270, 60, 26);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("genero:");
        panel.add(jLabel5);
        jLabel5.setBounds(30, 310, 51, 17);

        txtNOMBRE.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        panel.add(txtNOMBRE);
        txtNOMBRE.setBounds(100, 160, 210, 25);

        txtApellido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        panel.add(txtApellido);
        txtApellido.setBounds(100, 210, 200, 25);

        jcboGenero.setBackground(new java.awt.Color(204, 255, 255));
        jcboGenero.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jcboGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "masculino", "femenino" }));
        panel.add(jcboGenero);
        jcboGenero.setBounds(100, 310, 130, 27);

        botonBuscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botonBuscar.setText("Buscar");
        panel.add(botonBuscar);
        botonBuscar.setBounds(10, 100, 100, 33);
        panel.add(idPersonatxt);
        idPersonatxt.setBounds(340, 100, 50, 24);

        btnInsertar.setText("insertar");
        panel.add(btnInsertar);
        btnInsertar.setBounds(220, 470, 90, 32);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dni");
        panel.add(jLabel1);
        jLabel1.setBounds(40, 360, 31, 17);

        btnModificar.setText("Modificar");
        panel.add(btnModificar);
        btnModificar.setBounds(320, 470, 100, 32);

        txtClave.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        panel.add(txtClave);
        txtClave.setBounds(100, 360, 230, 25);

        btnLimpiar.setText("Limpiar");
        panel.add(btnLimpiar);
        btnLimpiar.setBounds(120, 470, 90, 32);

        txtPass.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        panel.add(txtPass);
        txtPass.setBounds(120, 100, 190, 25);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel6.setText("Registro de Personas ");
        panel.add(jLabel6);
        jLabel6.setBounds(70, 20, 290, 30);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 102));
        panel.add(jSeparator1);
        jSeparator1.setBounds(10, 60, 400, 10);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 102));
        panel.add(jSeparator2);
        jSeparator2.setBounds(0, 440, 420, 10);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel7.setText("Buscar por Dni:");
        panel.add(jLabel7);
        jLabel7.setBounds(20, 70, 150, 20);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setText("Celular:");
        panel.add(jLabel8);
        jLabel8.setBounds(20, 400, 70, 17);

        txtTelefono.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        panel.add(txtTelefono);
        txtTelefono.setBounds(100, 400, 230, 25);

        MEN1.setText("Menú");

        btnMostrarTabla.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnMostrarTabla.setText("Mostrar registro");
        MEN1.add(btnMostrarTabla);

        Men0.add(MEN1);

        setJMenuBar(Men0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDiaActionPerformed
        
    }//GEN-LAST:event_cboDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MEN1;
    public javax.swing.JMenuBar Men0;
    public javax.swing.JButton botonBuscar;
    public javax.swing.JButton btnElimiar;
    public javax.swing.JButton btnInsertar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JMenuItem btnMostrarTabla;
    private java.awt.Canvas canvas1;
    public javax.swing.JComboBox<String> cboAño;
    public javax.swing.JComboBox<String> cboDia;
    public javax.swing.JComboBox<String> cboMes;
    public javax.swing.JTextField idPersonatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    public javax.swing.JComboBox<String> jcboGenero;
    public javax.swing.JPanel panel;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtClave;
    public javax.swing.JTextField txtNOMBRE;
    public javax.swing.JTextField txtPass;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
